---
title: "Assignment 2 - Ram Yoogesh (20867060)"
output:
  pdf_document: default
---


```{r}
help("distributions")

```



```{r}
truncate <- function (ddist = dnorm, pdist = pnorm, qdist = qnorm, a = -inf, b = inf)
{

ddist <- function(){
  
}
  
pdist <- function()
{
}
qdist <- function ()
{
  
}

rdist <- function ()
{
  
}
demo_list = list(f1 = ddist, f2 = pdist, f3 = qdist, f4 = rdist)
return (demo_list)
}


```


```{r}
half_normal <- truncate(a = 2)
print(half_normal$a)
```

```{r}
half_normal <- truncate (a = 0)
xsample <- half_normal$rdist(300)
x <- seq(-3, 3, 0.01)
fx <- half_normal$ddist(x)
FX <- half_normal$pdist(x)
oldpar <- par (mfrow = c(1,2))
plot(x, fx, type = "1", main = "Half Normal Density")
plot(x, FX, type = "1", main = "Half Normal Distribution")
hist(xsample, main = "Half Normal Sample")
```


```{r}
library("fdrtool")


## density of half-normal compared with a corresponding normal
par(mfrow=c(1,2))

sd.norm = 0.64
x  = seq(0, 5, 0.01)
x2 = seq(-5, 5, 0.01)
plot(x, dhalfnorm(x, sd2theta(sd.norm)), type="l", xlim=c(-5, 5), lwd=2,
   main="Probability Density", ylab="pdf(x)")
lines(x2, dnorm(x2, sd=sd.norm), col=8 )


plot(x, phalfnorm(x, sd2theta(sd.norm)), type="l", xlim=c(-5, 5),  lwd=2,
   main="Distribution Function", ylab="cdf(x)")
lines(x2, pnorm(x2, sd=sd.norm), col=8 )

legend("topleft", 
c("half-normal", "normal"), lwd=c(2,1),
col=c(1, 8), bty="n", cex=1.0)

par(mfrow=c(1,1))


## distribution function

integrate(dhalfnorm, 0, 1.4, theta = 1.234)
phalfnorm(1.4, theta = 1.234)

## quantile function
qhalfnorm(-1) # NaN
qhalfnorm(0)
qhalfnorm(.5)
qhalfnorm(1)
qhalfnorm(2) # NaN

## random numbers
theta = 0.72
hz = rhalfnorm(10000, theta)
hist(hz, freq=FALSE)
lines(x, dhalfnorm(x, theta))

mean(hz) 
1/theta  # theoretical mean
```

